# Generated by Django 5.0.2 on 2024-03-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='link',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
