# Generated by Django 5.0.2 on 2024-03-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_preview_alter_lesson_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='owner',
        ),
    ]
